version: "3.9"
services:
  api:
    build:
      context: .
      args:
        host: postgres
        username: admin
        password: admin
        name: taskmdb
    expose:
      - 8089
    ports:
      - 8089:8089
    environment:
      - SERVER_PORT=8089
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
    volumes:
      - .:/app_dir
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORDs=${POSTGRES_PASSWORDs}
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_HOST=${POSTGRES_HOST}
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=taskmdb
      - POSTGRES_HOST=postgres
    volumes:
      - db_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
volumes:
  api:
  db_postgres:

networks:
  default:
    driver: bridge
