version: '3'
services:

    database:
      image: postgres:latest
      restart: always
      # entrypoint: env
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: taskservicedb
        POSTGRES_USER: taskservice
        POSTGRES_PASSWORD: taskservice
        HOST: database
      volumes:
        - database_data:/var/lib/postgresql/data

    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        HOST: database
      volumes:
        - ./:/usr/src/taskservice/
      links:
        - database
      depends_on:
        - database

volumes:
    database_data:
      driver: local
