version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/postgres:10.5-alpine

    working_directory: /go/src/github.com/Gidraff/task-manager-usecase

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - run: go test -v ./...


      - restore_cache:
          keys:
            - v1-pkg-cache